version: '3.3'
services:
    postgres:
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
        ports:
            - '5432:5432'
        volumes:
            - './init:/docker-entrypoint-initdb.d'
        restart: always
        container_name: db_odoo_temp
        image: 'postgres:10'
